[versions]
activity-compose = "1.9.2"
androidBeaconLibrary = "2.20.6"
androidPlugin = "8.6.0"
androidSdk-compile = "34"
androidSdk-min = "21"
androidSdk-target = "34"
androidSdk-automotive-min = "29"
androidSdk-wear-min = "26"
androidSdk-wear-target = "33"
appcompat = "1.7.0"
biometric = "1.1.0"
blurView = "version-2.0.5"
car-versions = "1.4.0"
changeLog = "3.5"
community-material-typeface = "7.0.96.1-kotlin"
compose-bom = "2024.09.00"
connectClient = "1.1.0-alpha07"
constraintlayout = "2.1.4"
coreKtx = "1.13.1"
core-splashscreen = "1.1.0-rc01"
cronet-embedded = "119.6045.31"
emojiJava = "5.1.1"
firebase-bom = "33.2.0"
firebaseAppdistributionGradle = "5.0.0"
fragment-ktx = "1.8.2"
googleServices = "4.4.2"
guava = "33.3.0-android"
healthServicesClient = "1.0.0-rc02"
hilt = "2.52"
iconics = "5.4.0"
jackson-module-kotlin = "2.13.5"
javaVersion = "11"
kotlinx-coroutines = "1.8.1"
kotlin = "2.0.20"
ksp = "2.0.20-1.0.24"
ktlint = "12.1.1"
lifecycle = "2.8.5"
material = "1.12.0"
media = "1.7.0"
media3 = "1.4.1"
navigation-compose = "2.7.7"
okhttp = "5.0.0-alpha.14"
paging = "3.3.2"
picasso = "2.8"
play-services-threadnetwork = "16.0.1"
play-services-home = "16.0.0"
play-services-location = "21.3.0"
play-services-wearable = "18.2.0"
preference-ktx = "1.2.1"
recyclerview = "1.3.2"
reorderable = "0.9.6"
retrofit = "2.9.0"
room = "2.6.1"
sentry-android = "7.14.0"
tools-desugar-jdk-libs = "2.1.2"
watchfaceComplicationsDataSourceKtx = "1.2.1"
wear = "1.3.0"
wear-compose-foundation = "1.3.1"
wear-compose-material = "1.0.0-alpha15"
wear-protolayout = "1.2.0"
wear-tiles = "1.4.0"
wear-tooling = "1.0.0"
wearPhoneInteractions = "1.0.1"
wearInput = "1.2.0-alpha02"
webkit = "1.11.0"
wear-remote-interactions = "1.0.0"
workRuntimeKtx = "2.9.1"
horologist = "0.5.28"
zxing = "4.3.0"
mpgraph = "v3.1.0"

[plugins]
android-application = { id = "com.android.application", version.ref = "androidPlugin" }
android-library = { id = "com.android.library", version.ref = "androidPlugin" }
firebase-appdistribution = { id = "com.google.firebase.appdistribution", version.ref = "firebaseAppdistributionGradle" }
google-services = { id = "com.google.gms.google-services", version.ref = "googleServices" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }

[libraries]
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activity-compose" }
android-beacon-library = { module = "org.altbeacon:android-beacon-library", version.ref = "androidBeaconLibrary" }
androidx-health-connect-client = { module = "androidx.health.connect:connect-client", version.ref = "connectClient" }
androidx-health-services-client = { module = "androidx.health:health-services-client", version.ref = "healthServicesClient" }
androidx-media = { module = "androidx.media:media", version.ref = "media" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-room-paging = { module = "androidx.room:room-paging", version.ref = "room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-watchface-complications-data-source-ktx = { module = "androidx.wear.watchface:watchface-complications-data-source-ktx", version.ref = "watchfaceComplicationsDataSourceKtx" }
androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "workRuntimeKtx" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
biometric = { module = "androidx.biometric:biometric", version.ref = "biometric" }
blurView = { module = "com.github.Dimezis:BlurView", version.ref = "blurView" }
car-core = { module = "androidx.car.app:app", version.ref = "car-versions" }
car-automotive = { module = "androidx.car.app:app-automotive", version.ref = "car-versions" }
car-projected = { module = "androidx.car.app:app-projected", version.ref = "car-versions" }
changeLog = { module = "com.github.AppDevNext:ChangeLog", version.ref = "changeLog" }
community-material-typeface = { module = "com.mikepenz:community-material-typeface", version.ref = "community-material-typeface" }
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }
compose-animation = { module = "androidx.compose.animation:animation" }
compose-foundation = { module = "androidx.compose.foundation:foundation" }
compose-material = { module = "androidx.compose.material:material" }
compose-material-icons-core = { module = "androidx.compose.material:material-icons-core" }
compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }
compose-runtime = { module = "androidx.compose.runtime:runtime" }
compose-ui = { module = "androidx.compose.ui:ui" }
compose-uiTooling = { module = "androidx.compose.ui:ui-tooling" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "core-splashscreen" }
cronet-embedded = { module = "org.chromium.net:cronet-embedded", version.ref = "cronet-embedded" }
emojiJava = { module = "com.vdurmont:emoji-java", version.ref = "emojiJava" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase-bom" }
firebase-messaging = { module = "com.google.firebase:firebase-messaging" }
fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragment-ktx" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
horologist-composables = { module = "com.google.android.horologist:horologist-composables", version.ref = "horologist" }
horologist-layout = { module = "com.google.android.horologist:horologist-compose-layout", version.ref = "horologist" }
iconics-compose = { module = "com.mikepenz:iconics-compose", version.ref = "iconics" }
iconics-core = { module = "com.mikepenz:iconics-core", version.ref = "iconics" }
jackson-module-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "jackson-module-kotlin" }
kotlinx-coroutines-guava = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-guava", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-play-services = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation-compose" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
material = { module = "com.google.android.material:material", version.ref = "material" }
media3-datasource-cronet = { module = "androidx.media3:media3-datasource-cronet", version.ref = "media3" }
media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "media3" }
media3-exoplayer-hls = { module = "androidx.media3:media3-exoplayer-hls", version.ref = "media3" }
media3-ui = { module = "androidx.media3:media3-ui", version.ref = "media3" }
paging-runtime = { module = "androidx.paging:paging-runtime", version.ref = "paging" }
paging-compose = { module = "androidx.paging:paging-compose", version.ref = "paging" }
play-services-threadnetwork = { module = "com.google.android.gms:play-services-threadnetwork", version.ref = "play-services-threadnetwork" }
play-services-home = { module = "com.google.android.gms:play-services-home", version.ref = "play-services-home" }
play-services-location = { module = "com.google.android.gms:play-services-location", version.ref = "play-services-location" }
picasso = { module = "com.squareup.picasso:picasso", version.ref = "picasso" }
play-services-wearable = { module = "com.google.android.gms:play-services-wearable", version.ref = "play-services-wearable" }
preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "preference-ktx" }
recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
reorderable = { module = "org.burnoutcrew.composereorderable:reorderable", version.ref = "reorderable" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-converter-jackson = { module = "com.squareup.retrofit2:converter-jackson", version.ref = "retrofit"  }
sentry-android = { module = "io.sentry:sentry-android", version.ref = "sentry-android" }
tools-desugar-jdk = { module = "com.android.tools:desugar_jdk_libs", version.ref = "tools-desugar-jdk-libs" }
wear = { module = "androidx.wear:wear", version.ref = "wear" }
wear-compose-foundation = { module = "androidx.wear.compose:compose-foundation", version.ref = "wear-compose-foundation" }
wear-compose-material = { module = "androidx.wear.compose:compose-material3", version.ref = "wear-compose-material" }
wear-compose-navigation = { module = "androidx.wear.compose:compose-navigation", version.ref = "wear-compose-foundation" }
wear-phone-interactions = { module = "androidx.wear:wear-phone-interactions", version.ref = "wearPhoneInteractions" }
wear-input = { module = "androidx.wear:wear-input", version.ref = "wearInput" }
wear-protolayout-expression = { module = "androidx.wear.protolayout:protolayout-expression", version.ref = "wear-protolayout" }
wear-protolayout-main = { module = "androidx.wear.protolayout:protolayout", version.ref = "wear-protolayout" }
wear-protolayout-material = { module = "androidx.wear.protolayout:protolayout-material", version.ref = "wear-protolayout" }
wear-remote-interactions = { module = "androidx.wear:wear-remote-interactions", version.ref = "wear-remote-interactions" }
wear-tiles = { module = "androidx.wear.tiles:tiles", version.ref = "wear-tiles" }
wear-tooling = { module = "androidx.wear:wear-tooling-preview", version.ref = "wear-tooling" }
webkit = { module = "androidx.webkit:webkit", version.ref = "webkit" }
zxing = { module = "com.journeyapps:zxing-android-embedded", version.ref = "zxing" }
mpgraph = { module = "com.github.PhilJay:MPAndroidChart", version.ref = "mpgraph" }

[bundles]
horologist = ["horologist-layout", "horologist-composables"]
media3 = ["media3-exoplayer", "media3-exoplayer-hls", "media3-ui"]
paging = ["paging-runtime", "paging-compose"]
wear-tiles = ["wear-tiles", "wear-protolayout-main", "wear-protolayout-expression", "wear-protolayout-material"]
