# ---------- IMPORTANT ----------
# You need to update the lock if you update or add a dependency
# you can do that with `./gradlew alldependencies --write-locks`
[versions]
activity-compose = "1.10.1"
androidBeaconLibrary = "2.21.1"
androidGradlePlugin = "8.10.0"
androidSdk-compile = "36"
androidSdk-min = "21"
androidSdk-target = "34"
androidSdk-automotive-min = "29"
androidSdk-wear-min = "26"
androidSdk-wear-target = "33"
androidxTestCore = "1.6.1"
androidxTestExt = "1.2.1"
androidxTestRules = "1.6.1"
androidxTestRunner = "1.6.2"
appcompat = "1.7.0"
biometric = "1.1.0"
blurView = "version-2.0.6"
car-versions = "1.4.0"
changeLog = "3.7.1"
community-material-typeface = "7.0.96.1-kotlin"
compose-bom = "2025.05.00"
connectClient = "1.1.0-rc01"
constraintlayout = "2.2.1"
coreKtx = "1.16.0"
core-splashscreen = "1.1.0-rc01"
core-remoteviews = "1.1.0"
cronet-embedded = "119.6045.31"
emojiJava = "5.1.1"
firebase-bom = "33.13.0"
firebaseAppdistributionGradle = "5.1.1"
fragment-ktx = "1.8.6"
glance = "1.1.1"
googleServices = "4.4.2"
guava = "33.4.6-android"
healthServicesClient = "1.1.0-alpha05"
hilt = "2.56.2"
iconics = "5.4.0"
improv = "0.1.1"
jackson-module-kotlin = "2.13.5" # WARNING: https://github.com/home-assistant/android/issues/3518
javaVersion = "11" # https://developer.android.com/studio/write/java11-minimal-support-table
junit = "5.12.2"
kotlinx-coroutines = "1.10.2"
kotlin = "2.1.20"
ksp = "2.1.20-2.0.1"
ktlint = "12.2.0"
leakcanaryAndroid = "2.14"
lifecycle = "2.9.0"
material = "1.12.0"
media = "1.7.0"
media3 = "1.6.1"
mockk = "1.14.2"
navigation-compose = "2.9.0"
okhttp = "5.0.0-alpha.14"
paging = "3.3.6"
coil = "3.1.0"
play-services-threadnetwork = "16.2.1"
play-services-home = "16.0.0"
play-services-location = "21.3.0"
play-services-wearable = "19.0.0"
preference-ktx = "1.2.1"
recyclerview = "1.4.0"
reorderable = "2.4.3"
retrofit = "2.12.0"
robolectric = "4.14.1"
room = "2.7.1"
runtimeLint = "1.8.1"
screenshot = "0.0.1-alpha09"
sentry-android = "8.11.1"
timber = "5.0.1"
tools-desugar-jdk-libs = "2.1.5"
turbine = "1.2.0"
watchfaceComplicationsDataSourceKtx = "1.2.1"
wear = "1.3.0"
wear-compose-foundation = "1.4.1"
wear-compose-material = "1.0.0-alpha37"
wear-protolayout = "1.2.1"
wear-tiles = "1.4.1"
wear-tooling = "1.0.0"
wearPhoneInteractions = "1.1.0"
wearInput = "1.2.0-alpha02"
webkit = "1.13.0"
wear-remote-interactions = "1.1.0"
workRuntimeKtx = "2.10.1"
zxing = "4.3.0"

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
firebase-appdistribution = { id = "com.google.firebase.appdistribution", version.ref = "firebaseAppdistributionGradle" }
google-services = { id = "com.google.gms.google-services", version.ref = "googleServices" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
screenshot = { id = "com.android.compose.screenshot", version.ref = "screenshot" }

# Plugins defined by this project in `:build-logic:convention` module.
homeassistant-android-application = { id = "homeassistant.android.application" }
homeassistant-android-common = { id = "homeassistant.android.common" }
homeassistant-android-dependencies = { id = "homeassistant.android.dependencies" }
homeassistant-android-flavor = { id = "homeassistant.android.flavor" }

[libraries]
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activity-compose" }
android-beacon-library = { module = "org.altbeacon:android-beacon-library", version.ref = "androidBeaconLibrary" }
android-gradle-plugin = { group = "com.android.tools.build", name = "gradle", version.ref = "androidGradlePlugin" }
androidx-glance-appwidget = { module = "androidx.glance:glance-appwidget", version.ref = "glance" }
androidx-glance-material = { module = "androidx.glance:glance-material", version.ref = "glance" }
androidx-glance-preview = { module = "androidx.glance:glance-preview", version.ref = "glance" }
androidx-glance-appwidget-preview = { module = "androidx.glance:glance-appwidget-preview", version.ref = "glance" }
androidx-glance-testing = { module = "androidx.glance:glance-testing", version.ref = "glance" }
androidx-glance-appwidget-testing = { module = "androidx.glance:glance-appwidget-testing", version.ref = "glance" }
androidx-health-connect-client = { module = "androidx.health.connect:connect-client", version.ref = "connectClient" }
androidx-health-services-client = { module = "androidx.health:health-services-client", version.ref = "healthServicesClient" }
androidx-media = { module = "androidx.media:media", version.ref = "media" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-room-paging = { module = "androidx.room:room-paging", version.ref = "room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-runtime-lint = { module = "androidx.compose.runtime:runtime-lint", version.ref = "runtimeLint" }
androidx-watchface-complications-data-source-ktx = { module = "androidx.wear.watchface:watchface-complications-data-source-ktx", version.ref = "watchfaceComplicationsDataSourceKtx" }
androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "workRuntimeKtx" }
androidx-test-core = { group = "androidx.test", name = "core", version.ref = "androidxTestCore" }
androidx-test-ext = { group = "androidx.test.ext", name = "junit-ktx", version.ref = "androidxTestExt" }
androidx-test-rules = { group = "androidx.test", name = "rules", version.ref = "androidxTestRules" }
androidx-test-runner = { group = "androidx.test", name = "runner", version.ref = "androidxTestRunner" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
biometric = { module = "androidx.biometric:biometric", version.ref = "biometric" }
blurView = { module = "com.github.Dimezis:BlurView", version.ref = "blurView" }
car-core = { module = "androidx.car.app:app", version.ref = "car-versions" }
car-automotive = { module = "androidx.car.app:app-automotive", version.ref = "car-versions" }
car-projected = { module = "androidx.car.app:app-projected", version.ref = "car-versions" }
changeLog = { module = "com.github.AppDevNext:ChangeLog", version.ref = "changeLog" }
coil-oktthp = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coil" }
coil-svg = { module = "io.coil-kt.coil3:coil-svg", version.ref = "coil" }
coil-views = { module = "io.coil-kt.coil3:coil", version.ref = "coil" }
community-material-typeface = { module = "com.mikepenz:community-material-typeface", version.ref = "community-material-typeface" }
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }
compose-animation = { module = "androidx.compose.animation:animation" }
compose-foundation = { module = "androidx.compose.foundation:foundation" }
compose-material = { module = "androidx.compose.material:material" }
compose-material-icons-core = { module = "androidx.compose.material:material-icons-core" }
compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }
compose-runtime = { module = "androidx.compose.runtime:runtime" }
compose-ui = { module = "androidx.compose.ui:ui" }
compose-uiTooling = { module = "androidx.compose.ui:ui-tooling" }
compose-ui-test = { group = "androidx.compose.ui", name = "ui-test-junit4" }
compose-ui-testManifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "core-splashscreen" }
core-remoteviews = { module = "androidx.core:core-remoteviews", version.ref = "core-remoteviews" }
cronet-embedded = { module = "org.chromium.net:cronet-embedded", version.ref = "cronet-embedded" }
emojiJava = { module = "com.vdurmont:emoji-java", version.ref = "emojiJava" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase-bom" }
firebase-messaging = { module = "com.google.firebase:firebase-messaging" }
fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragment-ktx" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
iconics-compose = { module = "com.mikepenz:iconics-compose", version.ref = "iconics" }
iconics-core = { module = "com.mikepenz:iconics-core", version.ref = "iconics" }
improv = { module = "org.openhomefoundation.improv-wifi:sdk-android", version.ref = "improv" }
jackson-module-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "jackson-module-kotlin" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
junit-vintage-engine = { module = "org.junit.vintage:junit-vintage-engine" }
kotlin-gradle-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinx-coroutines-guava = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-guava", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-play-services = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
leakcanary-android = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakcanaryAndroid" }
leakcanary-android-instrumentation = { module = "com.squareup.leakcanary:leakcanary-android-instrumentation", version.ref = "leakcanaryAndroid" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation-compose" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
material = { module = "com.google.android.material:material", version.ref = "material" }
media3-datasource-cronet = { module = "androidx.media3:media3-datasource-cronet", version.ref = "media3" }
media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "media3" }
media3-exoplayer-hls = { module = "androidx.media3:media3-exoplayer-hls", version.ref = "media3" }
media3-ui = { module = "androidx.media3:media3-ui", version.ref = "media3" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
paging-runtime = { module = "androidx.paging:paging-runtime", version.ref = "paging" }
paging-compose = { module = "androidx.paging:paging-compose", version.ref = "paging" }
play-services-threadnetwork = { module = "com.google.android.gms:play-services-threadnetwork", version.ref = "play-services-threadnetwork" }
play-services-home = { module = "com.google.android.gms:play-services-home", version.ref = "play-services-home" }
play-services-location = { module = "com.google.android.gms:play-services-location", version.ref = "play-services-location" }
play-services-wearable = { module = "com.google.android.gms:play-services-wearable", version.ref = "play-services-wearable" }
preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "preference-ktx" }
recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
reorderable = { module = "sh.calvin.reorderable:reorderable", version.ref = "reorderable" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-converter-jackson = { module = "com.squareup.retrofit2:converter-jackson", version.ref = "retrofit"  }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
sentry-android-core = { module = "io.sentry:sentry-android-core", version.ref = "sentry-android" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
tools-desugar-jdk = { module = "com.android.tools:desugar_jdk_libs", version.ref = "tools-desugar-jdk-libs" }
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }
wear = { module = "androidx.wear:wear", version.ref = "wear" }
wear-compose-foundation = { module = "androidx.wear.compose:compose-foundation", version.ref = "wear-compose-foundation" }
wear-compose-material = { module = "androidx.wear.compose:compose-material3", version.ref = "wear-compose-material" }
wear-compose-navigation = { module = "androidx.wear.compose:compose-navigation", version.ref = "wear-compose-foundation" }
wear-phone-interactions = { module = "androidx.wear:wear-phone-interactions", version.ref = "wearPhoneInteractions" }
wear-input = { module = "androidx.wear:wear-input", version.ref = "wearInput" }
wear-protolayout-expression = { module = "androidx.wear.protolayout:protolayout-expression", version.ref = "wear-protolayout" }
wear-protolayout-main = { module = "androidx.wear.protolayout:protolayout", version.ref = "wear-protolayout" }
wear-protolayout-material = { module = "androidx.wear.protolayout:protolayout-material", version.ref = "wear-protolayout" }
wear-remote-interactions = { module = "androidx.wear:wear-remote-interactions", version.ref = "wear-remote-interactions" }
wear-tiles = { module = "androidx.wear.tiles:tiles", version.ref = "wear-tiles" }
wear-tooling = { module = "androidx.wear:wear-tooling-preview", version.ref = "wear-tooling" }
webkit = { module = "androidx.webkit:webkit", version.ref = "webkit" }
zxing = { module = "com.journeyapps:zxing-android-embedded", version.ref = "zxing" }

[bundles]
androidx-test =["androidx-test-core", "androidx-test-ext", "androidx-test-rules", "androidx-test-runner"]
androidx-compose-ui-test = ["compose-ui-test", "compose-ui-testManifest"]
androidx-glance = ["androidx-glance-appwidget", "androidx-glance-appwidget-preview", "androidx-glance-material", "androidx-glance-preview"]
androidx-glance-testing = ["androidx-glance-testing", "androidx-glance-appwidget-testing"]
coil = ["coil-views", "coil-oktthp", "coil-svg"]
media3 = ["media3-exoplayer", "media3-exoplayer-hls", "media3-ui"]
paging = ["paging-runtime", "paging-compose"]
wear-tiles = ["wear-tiles", "wear-protolayout-main", "wear-protolayout-expression", "wear-protolayout-material"]
