blank_issues_enabled: false
contact_links:
  - name: Issue or suggestion for the app documentation
    url: https://github.com/home-assistant/companion.home-assistant/issues
    about: Please report any errors, missing information, or suggestions for the companion app documentation here.
  - name: Issue or suggestion for the developer documentation
    url: https://github.com/home-assistant/developers.home-assistant/issues
    about: Please report any errors, missing information, or suggestions for the developer documentation here.
  - name: Request a feature for the Android application
    url: https://github.com/orgs/home-assistant/discussions/new?category=android
    about: Request a new feature for the Android application.
  - name: Problem with your dashboard
    url: https://github.com/home-assistant/frontend/issues
    about: Most of the app's interface is provided by the Home Assistant frontend (WebView). Please report dashboard issues here.
  - name: I have a question or need support
    url: https://www.home-assistant.io/help
    about: GitHub is for tracking bugs and feature requests. For help and support, please visit our help page.
  - name: I'm not sure where to go
    url: https://www.home-assistant.io/join-chat
    about: If you're unsure where to report your issue or ask your question, join our chat and we'll help
