name: Bump our Calendar Version

on:
  workflow_dispatch:
  schedule:
    - cron: '30 3 1 * *'
jobs:
  tag:
    name: Tag Monthly Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get Current Time
        uses: josStorer/get-current-time@v2.1.2
        id: current-time

      - name: Bump Calendar Version
        uses: rickstaa/action-create-tag@v1.7.2
        with:
          tag: ${{ steps.current-time.outputs.year }}.${{ steps.current-time.outputs.month }}.0
