name: Production Deploy

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  release:
    types: [released]

env:
  SUPPLY_UPLOAD_MAX_RETRIES: 5

permissions:
  contents: read

jobs:
  play_promote_production:
    name: Play Publish Production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: ruby/setup-ruby@09a7688d3b55cf0e976497ff046b70949eeaccfd # v1.288.0
        with:
          ruby-version: "4.0.1"
          bundler-cache: true

      - uses: ./.github/actions/inflate-secrets
        name: Inflate Secrets
        with:
          keystore: ${{ secrets.ORIGINAL_KEYSTORE_FILE }}
          google-services: ${{ secrets.GOOGLESERVICES }}
          firebase-creds: ${{ secrets.FIREBASECREDS }}
          playstore-creds: ${{ secrets.PLAYSTORECREDS }}

      - name: Promote Beta to Production Play Store
        run: bundle exec fastlane promote_to_production
