name: Production Deploy

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  release:
    types: [released]

env:
  SUPPLY_UPLOAD_MAX_RETRIES: 5

permissions:
  contents: read

jobs:
  play_promote_production:
    name: Play Publish Production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - uses: ruby/setup-ruby@d697be2f83c6234b20877c3b5eac7a7f342f0d0c # v1.269.0
        with:
          ruby-version: "3.4.7"
          bundler-cache: true

      - uses: ./.github/actions/inflate-secrets
        name: Inflate Secrets
        with:
          keystore: ${{ secrets.ORIGINAL_KEYSTORE_FILE }}
          google-services: ${{ secrets.GOOGLESERVICES }}
          firebase-creds: ${{ secrets.FIREBASECREDS }}
          playstore-creds: ${{ secrets.PLAYSTORECREDS }}

      - name: Promote Beta to Production Play Store
        run: bundle exec fastlane promote_to_production
