name: Tag Weekly Release

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * 0"
jobs:
  tag:
    name: Tag Weekly Release
    runs-on: ubuntu-latest
    permissions:
      actions: write # Start workflows onPush and prepareNextRelease
      contents: write # Allow pushing tags
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup-build-env
        with:
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}

      - name: Tag Weekly Release
        env:
          GITHUB_TOKEN: ${{ secrets.TAG_PUSH_TOKEN }}
        run: ./gradlew :reckonTagPush -Preckon.stage=final

      - name: Trigger Workflow
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'onPush.yml',
              ref: 'main',
              inputs: {
                "beta": "true",
              },
            })

      - name: Trigger Prepare Next Release
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'prepareNextRelease.yml',
              ref: 'main',
            })
