name: Tag Weekly Release

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * 0'
jobs:
  tag:
    name: Tag Weekly Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4.5.0
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Tag Weekly Release
        env:
          GITHUB_TOKEN: ${{ secrets.TAG_PUSH_TOKEN }}
        run: ./gradlew :reckonTagPush -Preckon.stage=final

      - name: Trigger Workflow
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'onPush.yml',
              ref: 'master',
              inputs: {
                "beta": "true",
              },
            })
